insults = ["YOU MAKE ME WISH I HAD MORE MIDDLE FINGERS.",
           "Trollex is a cuck",
		   "You wasteful cockqueen",
		   "You manipulative numbnuts",
		   "You weak-willed ass clown",
		   "YOU PEOPLE ARE MORE STUPID THAN A BLOCK OF WOOD.",
		   "IN APPEARANCE AND WORDS YOU SIMULATE MODESTY, BUT YOU ARE SO SWOLLEN WITH HAUGHTINESS, ARROGANCE, PRIDE, MALICE, VILLAINY, RASHNESS, SUPERCILIOUSNESS, IGNORANCE, AND STUPIDITY THAT THERE IS NOTHING TO SURPASS YOU.",
		   "IF ALL THE IDIOTS IN ALL THE VILLAGES LEFT THEIR VILLAGES AND FORMED THEIR OWN VILLAGE OF IDIOTS IN THAT VILLAGE YOU WOULD BE THE VILLAGE IDIOT.",
		   "YOU ARE FAT AND HAVE BODY ODOR!",
		   "YOU'RE THE LOAD YOUR MOTHER SHOULD’VE SWALLOWED AND THEN VIOLENTLY SHIT ON YOUR DAD'S MICRO PENIS.",
		   "YOU'RE A FAILED ABORTION WHOSE BIRTH CERTIFICATE IS AN APOLOGY FROM THE CONDOM FACTORY.",
		   "YOUR MOTHER FUCKS FOR BRICKS SO SHE CAN BUILD YOUR SISTER A WHORE HOUSE.",
		   "PUT A DENTURE IN YOU ASSHOLE AND LAUGH TO THE COCK."
           ]
Random rnd = new Random()
 
//println(rnd.next(102))

player.realmSay("${insults[rnd.nextInt(insults.size())]}", "PUBLIC")
